name: Generate Plots

on:
  push:
    paths:
      - 'index.html'

jobs:
  generate-plots:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Choose the appropriate Python version

      - name: Install Dependencies
        run: pip install pandas matplotlib altair

      - name: Run Python Script
        run: python generate_plots.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate JSON files"
          git push
